name: edibuddy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  google_sign_in: ^6.1.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  lottie: ^3.0.0
  file_picker: ^8.1.6
  firebase_storage: ^12.3.7
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  firebase_remote_config: ^5.2.0
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.6.1
  flutter_form_builder: ^9.6.0
  form_builder_validators: ^11.1.1
  google_places_flutter: ^2.0.9
  intl: ^0.19.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  firebase_app_check: ^0.3.1+7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/images/logo.png # Path to your logo
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center


flutter:
  uses-material-design: true


  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo.png
    - assets/animations/
    - assets/icons/
    - assets/logo.svg
    - assets/data/india_locations.json
    - assets/icons/edibuddylogo.png

